[package]
name = "certificate-revocation"
version = "0.1.0"
edition = "2021"
license = "MIT"


# Cargo.toml
[profile.release]
panic = "abort"
overflow-checks = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
